using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Reflection;

namespace Wolfgang.Etl.DbClient;

/// <summary>
/// Generates SQL commands from <see cref="TableAttribute"/>, <see cref="ColumnAttribute"/>,
/// and <see cref="KeyAttribute"/> annotations on a POCO type.
/// </summary>
internal static class DbCommandBuilder
{
    /// <summary>
    /// Generates a SELECT statement for all mapped columns.
    /// Requires <see cref="TableAttribute"/> on the type.
    /// </summary>
    /// <exception cref="InvalidOperationException">
    /// Thrown when the type does not have a <see cref="TableAttribute"/>.
    /// </exception>
    internal static string BuildSelect<T>()
    {
        var type = typeof(T);
        var table = GetTableName(type);
        var columns = GetColumnMappings(type);

        if (columns.Count == 0)
        {
            return $"SELECT * FROM {table}";
        }

        var columnList = string.Join
        (
            ", ",
            columns.Select(c => string.Equals(c.ColumnName, c.PropertyName, StringComparison.Ordinal)
                ? c.ColumnName
                : $"{c.ColumnName} AS {c.PropertyName}")
        );

        return $"SELECT {columnList} FROM {table}";
    }



    /// <summary>
    /// Generates an INSERT statement for all mapped non-key columns.
    /// If no <see cref="KeyAttribute"/> columns exist, all columns are included.
    /// Requires <see cref="TableAttribute"/> on the type.
    /// </summary>
    /// <exception cref="InvalidOperationException">
    /// Thrown when the type does not have a <see cref="TableAttribute"/>.
    /// </exception>
    internal static string BuildInsert<T>()
    {
        var type = typeof(T);
        var table = GetTableName(type);
        var columns = GetColumnMappings(type);
        var keys = GetKeyProperties(type);

        // Exclude [Key] + [DatabaseGenerated(Identity)] columns from INSERT.
        // Non-identity keys (e.g., composite keys) are included since they're
        // user-assigned values.
        var insertColumns = keys.Count > 0
            ? columns.Where(c => !IsAutoGeneratedKey(c.Property, keys)).ToList()
            : columns;

        if (insertColumns.Count == 0)
        {
            insertColumns = columns;
        }

        if (insertColumns.Count == 0)
        {
            throw new InvalidOperationException
            (
                $"Type '{type.FullName}' has no mapped columns for INSERT. " +
                "Ensure at least one public instance property is not decorated with [NotMapped]."
            );
        }

        var columnList = string.Join(", ", insertColumns.Select(c => c.ColumnName));
        var paramList = string.Join(", ", insertColumns.Select(c => $"@{c.PropertyName}"));

        return $"INSERT INTO {table} ({columnList}) VALUES ({paramList})";
    }



    /// <summary>
    /// Generates an UPDATE statement using <see cref="KeyAttribute"/> columns in the WHERE clause.
    /// Requires <see cref="TableAttribute"/> and at least one <see cref="KeyAttribute"/> property.
    /// </summary>
    /// <exception cref="InvalidOperationException">
    /// Thrown when the type does not have a <see cref="TableAttribute"/> or
    /// no properties are decorated with <see cref="KeyAttribute"/>.
    /// </exception>
    internal static string BuildUpdate<T>()
    {
        var type = typeof(T);
        var table = GetTableName(type);
        var columns = GetColumnMappings(type);
        var keys = GetKeyProperties(type);

        if (keys.Count == 0)
        {
            throw new InvalidOperationException
            (
                $"Type '{type.FullName}' has no properties decorated with [Key]. " +
                "UPDATE requires at least one key property for the WHERE clause."
            );
        }

        var keyNames = new HashSet<string>(keys.Select(k => k.Name), StringComparer.Ordinal);
        var setColumns = columns.Where(c => !keyNames.Contains(c.PropertyName)).ToList();
        var whereColumns = columns.Where(c => keyNames.Contains(c.PropertyName)).ToList();

        if (setColumns.Count == 0)
        {
            throw new InvalidOperationException
            (
                $"Type '{type.FullName}' has no non-key columns for the SET clause. " +
                "UPDATE requires at least one property that is not decorated with [Key]."
            );
        }

        if (whereColumns.Count == 0)
        {
            throw new InvalidOperationException
            (
                $"Type '{type.FullName}' has [Key] properties but none are mapped columns. " +
                "Ensure key properties are not decorated with [NotMapped]."
            );
        }

        var setClause = string.Join(", ", setColumns.Select(c => $"{c.ColumnName} = @{c.PropertyName}"));
        var whereClause = string.Join(" AND ", whereColumns.Select(c => $"{c.ColumnName} = @{c.PropertyName}"));

        return $"UPDATE {table} SET {setClause} WHERE {whereClause}";
    }



    // ------------------------------------------------------------------
    // Private helpers
    // ------------------------------------------------------------------

    private static string GetTableName(Type type)
    {
        var attr = type.GetCustomAttribute<TableAttribute>();
        if (attr == null)
        {
            throw new InvalidOperationException
            (
                $"Type '{type.FullName}' does not have a [Table] attribute. " +
                "Auto-generated SQL requires [Table(\"name\")] on the record type, " +
                "or pass a custom command text to the constructor."
            );
        }

        return attr.Name;
    }



    private static List<ColumnMapping> GetColumnMappings(Type type)
    {
        var mappings = new List<ColumnMapping>();

        foreach (var prop in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
        {
            if (prop.GetCustomAttribute<NotMappedAttribute>() != null)
            {
                continue;
            }

            var columnAttr = prop.GetCustomAttribute<ColumnAttribute>();
            var columnName = columnAttr?.Name ?? prop.Name;

            mappings.Add(new ColumnMapping(prop, columnName, prop.Name));
        }

        return mappings;
    }



    private static List<PropertyInfo> GetKeyProperties(Type type)
    {
        return type.GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(p => p.GetCustomAttribute<KeyAttribute>() != null)
            .ToList();
    }



    private static bool IsAutoGeneratedKey(PropertyInfo property, List<PropertyInfo> keys)
    {
        if (!keys.Any(k => string.Equals(k.Name, property.Name, StringComparison.Ordinal)))
        {
            return false;
        }

        var dbGenerated = property.GetCustomAttribute<DatabaseGeneratedAttribute>();
        return dbGenerated?.DatabaseGeneratedOption == DatabaseGeneratedOption.Identity;
    }



    private sealed class ColumnMapping
    {
        public ColumnMapping(PropertyInfo property, string columnName, string propertyName)
        {
            Property = property;
            ColumnName = columnName;
            PropertyName = propertyName;
        }

        public PropertyInfo Property { get; }
        public string ColumnName { get; }
        public string PropertyName { get; }
    }
}
